apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
 name: model
 labels:
  role: model
spec:
 targetRef:
  apiVersion: "apps/v1"
  kind: Deployment
  name: model
 updatePolicy:
  updateMode: "Auto"
 resourcePolicy:
  containerPolicies:
  - containerName: '*'
    minAllowed:
     cpu: 50m
     memory: 64Mi
    maxAllowed:
     cpu: 500m
     memory: 512Mi
    controlledResources: ["cpu", "memory"]